spring:
  application:
    name: commander-service

  # Configuração do Banco de Dados (Conecta no seu Docker)
  datasource:
    url: jdbc:postgresql://localhost:5432/uptime_db
    username: admin
    password: password123
    driver-class-name: org.postgresql.Driver

  # JPA / Hibernate (Cria as tabelas automaticamente para dev)
  jpa:
    hibernate:
      ddl-auto: update # Em produção usamos 'validate'
    show-sql: true
    properties:
      "[hibernate.format_sql]": true
      "[hibernate.dialect]": org.hibernate.dialect.PostgreSQLDialect

  # Configuração do RabbitMQ (Fila)
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: password123

# Configuração do Actuator (Para Monitoramento e K8s Probes)
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics